### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by safapps** [cesarvr/react-native-pdf-generator#3]
This error is happening in some Androids, it happened to me on Android 8 and Android 10:

The error line follows:

at com.pdf.generator.OffscreenBrowser.<init> (OffscreenBrowser.java:20)
  at com.pdf.generator.PDFGenerator.fromHTML (PDFGenerator.java:62)
react-native version 0.59.9

Thanks for the beautiful library

**Comment by safapps** [comment]
Can someone help please?

**Comment by cesarvr** [comment]
Hey @safapps 

Sorry I haven't updated the plugin a while ago, I checked it yesterday and it seems that the API I use for the plugin are deprecated. When I get some free time I'll update it. 

Cheers.

**Comment by cesarvr** [comment]
Hi @safapps 

I have updated the library to run on react-native so it should run now on Android >8, you just need to upgrade to the [1.5.0](https://www.npmjs.com/package/rn-pdf-generator) version, this should do it: 

```sh
npm install rn-pdf-generator@1.5.0 -s
```

If you need an working example you can use [this one...](https://github.com/cesarvr/ReactNativePDFExample)


Cheers.

**Comment by safapps** [comment]
@cesarvr Thank you very much for this quick response, I will update my project, your library is incredible and very light!

**Comment by safapps** [comment]
Hi @cesarvr after upgrading to version 1.5.0 still gave this error when testing on the Android emulator, the interesting thing is that it happens intermittently, most of the time it works correctly, this error in PDF.fromHTML, follow the message mistake:
"Calling display methods on a thread other than the user interface"
follow the screenshot of the error:
[https://1drv.ms/u/s!AhJHgZvM402SgocGhhGlG4wN12AnDA?e=yC7nnq](url)
[https://1drv.ms/u/s!AhJHgZvM402SgocHEUeI28e4w1bi9A?e=lhpMBl](url)

I'm sorry for the bad English

**Comment by cesarvr** [comment]
Hey @safapps , I think I fix the problem for version **1.6.0**, it was an issue was that the plugin was trying to do a lot of work in a thread that doesn't belong to UI rendering. I move that so now It should work, giving those errors/warning messages.  

[https://www.npmjs.com/package/rn-pdf-generator](https://www.npmjs.com/package/rn-pdf-generator)

**Comment by safapps** [comment]
**error: cannot find symbol
import androidx.annotation.RequiresApi;**

Hi @cesarvr , I can't test it, my application is breaking when compiling, because my react native version doesn't have androidx, is there any other way to import requiresApi other than androidx?
Thanks.

**Comment by cesarvr** [comment]
That's because I upgraded the library to Androidx, you can do this: 

- Change manually the import package to use : 

```java
import android.support.annotation.RequiresApi;
```
Or you can upgrade your project to [AndroidX](https://developer.android.com/jetpack/androidx/migrate) and last version of react-native. 

[More info on upgrading](https://github.com/invertase/react-native-firebase/issues/1588#issuecomment-503094221)
