### ISSUE TITLE
Deprecated API UIWebView

### ISSUE THREAD

**Issue by Serginh0** [cesarvr/react-native-pdf-generator#6]
Hi csarvr.

Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability.

Apple is launching this message saying that UIWEBVIEW is depreciated and in rn-pdf-generator has UIWEBVIEW in /rn-pdf-generator/ios/BNHtmlPdfKit.m, has some way to update manually or you will release some version with the fix ?
Thank you very much.

**Comment by Serginh0** [comment]
@cesarvr help me 🚶

**Comment by cesarvr** [comment]
@Serginh0  Sorry for late response.  I'm very busy lately.  : )

Sure I think is a simple change, you can just  remove the deprecated methods similar to this [ fix. ](https://github.com/cesarvr/pdf-generator/commit/cb1fe8ada871e933a69564dad8df2c5bbd7bf3cd#diff-20f3cb6c1aba7b3afc55723eebed8254).  I'll try to do it this weekend, but you can give it a try if you want and send a pull request.

**Comment by Serginh0** [comment]
thank you very much for the reply friend, i will delete these codes and test later. As I don't know anything about that language I thought that if I excluded it would generate some error.
But if I can do it on the weekend without any problems, I'm not in such a hurry. Thank you very much for the library.

**Comment by cesarvr** [comment]
@Serginh0 this should be[ fix now](https://github.com/cesarvr/react-native-pdf-generator/commit/d797e5725355e070ebd8a56876f72c6ceaf3c5a9#diff-cad5f816ea283ed636878f95183c54f7), you just need to update to [version 1.6.1](https://www.npmjs.com/package/rn-pdf-generator).

**Comment by Serginh0** [comment]
Hi @cesarvr, as i said earlier, i had to update my project because of the UIWEBVIEW error, i am currently with react native 0.62.2.
I updated the rn-pdf-generator to 1.6.1 and solved the UIWEBVIEW error, however the PDF.fromHTML method is undefined in this new version of react native (0.62.2), in version 0.59.9 it works perfectly, example of the error in Photograph:
https://drive.google.com/file/d/1hCwkEBmeATUmdBsLT5otkEdlFMXtqZr5/view?usp=sharing
Do you know if there is any way around the error? thanks in advance for the return.

**Comment by Serginh0** [comment]
Hi @cesarvr all well? can I get around this situation in any way?
I'm just depending on it to upload the app to the Apple Store.
Thanks.

**Comment by cesarvr** [comment]
I made the adjustment to be compatible with react ``0.6x``. The latest [version 1.6.4](https://www.npmjs.com/package/rn-pdf-generator) it should work well with ``podman``.
